#!/bin/bash


if [ $# -lt 2 ]; then
   echo "Usage: 
                $0 host_address service_port

                e.g. check HDFS service 

                $0 etu-master 9000
        "
        exit 0
else

   # make sure fast ping exist & in case if fast ping installed in sbin
   if [ `which fping >/dev/null ; echo $?` == 0 ]; then
      if [ $USER == root ]; then
         _ping="fping -c1 -t100"
      else
         _ping="ping -c1 -w2"
      fi
   else
      _ping="ping -c1 -w2"
   fi

   $_ping $1 >/dev/null
   if [ $? != 0 ]; then
      echo "ERROR: cant reach target host: $1"
   else
      (echo >/dev/tcp/$1/$2) &>/dev/null
      if [ $? != 0 ]; then
         echo "ERROR: service port ($2) is not reachable from host: $1"
      else
         echo "PASS: Service port ($2) reachable (host: $1)"
      fi
   fi
fi

