#!/bin/bash

source /opt/etu/etc/config.properties

info() {
    echo -e "`date +%c` - INFO: $* \n"
}

_conn_etu () {

  echo -n "Etu web management console password: " 
  read -s ETU_ADMPASS
  until ! [[ "y$ETU_ADMPASS" = "y" ]]
  do
     echo -n "Etu web management console password: " 
     read -s ETU_ADMPASS
  done
   
  local _etu_web="https://$_master_fqdn" 
  local _master_fqdn=$USER_HOST_NAME.$USER_DOMAIN
  local _adm_acc=admin
  local _cache=$HOME/.header
  local _curl="curl --insecure"
  local _etu_mod="HadoopDfsModule"
  local _etu_web="https://$_master_fqdn"
  local _adm_pass="${ETU_ADMPASS}" # default password for etu web admin
  info "Restart HDFS service from Etu management console"
  $_curl -s -d "user=$_adm_acc&password=$_adm_pass" --dump-header $_cache "$_etu_web/login.html" 
 
  info "List all deployed cluster services:" 
  $_curl -s -d "service=$_etu_mod" -L -b $_cache "$_etu_web/module/serviceList.do" | python -mjson.tool
  #info "Cleanup web cache"
  rm -f $_cache

}

_conn_etu

# end
