#!/bin/bash

_workers=(`source /opt/etu/etc/config.properties ; grep $USER_HOST_PREFIX- /etc/hosts  | grep -v $USER_HOST_NAME |grep -v $PRIVATE_HOST_NAME |grep -v $PRIVATE_HOST_PREFIX | awk '{print $(NF)}'`)
_inst_root="/var/disk/a/hadoop"

echo "INFO: total defined workers: ${#_workers[@]}"
echo "INFO: list of all workers: ${_workers[@]}"

for i in ${_workers[@]};
do
   if [ `fping -c1 -t50 $i >&/dev/null ; echo $?` == 0 ]; then
      echo "Create impalal installation folder at worker: $i "
      ssh $i mkdir $_inst_root/impala
      echo "Force etu as installation root ownership"
      ssh $i chown -R etu.etu $_inst_root/impala
      echo "Create symlink to default package root"
      ssh $i ln -s $_inst_root/impala /opt
   else
      echo "WARN: cant reach worker: $i"
   fi
done
