#!/bin/bash

if [ $# -lt 0 ]; then
   echo "Usage:
		$0 full-path-HDFS-file
	"
exit 1
fi

  tf=`mktemp /tmp/XXXXXX`
  hadoop fsck $1 -files -blocks -racks > $tf
  if [ $? != 0 ]; then
     echo "ERROR: fail performing file consistent check of $1"
     exit 1
     rm -f $tf
  fi

  echo ""; echo "Distribution of block distribution across all registered cluster nodes:"
  echo ""
  tb=`grep BP $tf | wc -l`
  grep BP $tf | awk '{print $(NF)}' | sort | uniq -c | sort -rn > $tf.1
  tbn=(`awk '{print $1}' $tf.1`)
  tn=(`awk '{print $2}' $tf.1`)

  echo "Total number of blocks of queried files           : $tb"
  echo "Total number of racks/datanodes posses data blocks: ${#tn[@]}"
  let j=0
  for i in ${tbn[@]}
  do
     echo -e "\t racks/datanodes: ${tn[$j]} - blocks: $i"
     let j+=1
  done
  echo ""
  echo "Statistics of block distribution:"
  cat $tf.1

  echo ""
  echo "File $1 summary report:"
  sed -n '/^Status:/,/FSCK ended/p' $tf

  rm -f $tf $tf.1

# end 
