#!/bin/bash

#cd /home/$USER/git/etu-appliance/build-tool
if [ ! -d $HOME/Etu ]; then
   echo "Cant find Etu working directory under $HOME, skip now!"
else
   cd $HOME/Etu
   if [ -f etu_build.sh ]; then
      echo "INFO: adopt etu default builder util"
      _builder=etu_build.sh
   elif [ -f etu_build_demo ]; then
        echo "INFO: found build demo, switch using build demo now!"
        _builder=etu_build_demo
   else
      echo "ERROR: Cant find etu build util"
      exit 1
   fi
   chmod 755 $_builder
   $_builder --resetvm
   VBoxManage startvm test_NN --type headless
   echo "INFO: Wait Etu Master deployment and system image cloning"
   sleep 30;
   
   ./etu_build_auto --lic ../examples/licenses/developing.VMs/developing.VMs.license
   echo "INFO: Wait 120sec for Master service initialization and will resume powering on Workers"
   sleep 120;
   VBoxManage modifyvm test_DN_1 --memory 4000
   VBoxManage modifyvm test_DN_2 --memory 4000
   VBoxManage startvm test_DN_1 --type headless
   VBoxManage startvm test_DN_2 --type headless
fi
# end


