#! /bin/sh

source /etc/profile
_root="/root/LC_cron"

#_baseName=local_syslog-ng.etu-6.log
_baseName=tcp_syslog-ng.etu-5.log
_baseName2=local_syslog-ng.etu-5.log
# local_syslog-ng.etu-6.log-hourly-20130529
_date=`date +%Y%m%d`
_date2=`date +%Y%m%d%H`
_ext=-hourly-CST-$_date
_ext2=-hourly-CST-$_date2

_logroot="/opt/var/log/syslog-ng"
_log=$_logroot/$_baseName$_ext
_log2=$_logroot/$_baseName$_ext2

echo "INFO: rotating logfile $_baseName now ..."
if [ ! -f $_root/syslog-ng ]; then
   echo "ERROR: cant find lograte config file, exit now!"; exit 1
else
   /usr/sbin/logrotate -v -f $_root/syslog-ng
fi

echo ""
if [ ! -f $_log ]; then
   echo "ERROR: logfile $_log not exist! problem with log file rotation?"
   exit 1
else
   echo "INFO: rename logfile and append extra date format (inc hour): $_log to $_log2"
   mv $_log $_log2
   echo "INFO: rename also default system log file, e.g.: basename local_syslog-ng.`hostname`"
   echo "      $_logroot/$_baseName2$_ext to $_logroot/$_baseName2$_ext2"
   mv $_logroot/$_baseName2$_ext $_logroot/$_baseName2$_ext2
fi

# upload to etu master now
echo "upoading to etu-master via private channel ..."
echo "create tranferred lock file and transfer to master as well ..."
touch $_log2.copied
su - jason -c "lftp -u jason,password etu-private-master -e 'put $_log2 $_log2.copied; exit;'"
rm $_log2.copied
# end
