#!/bin/bash

source /home/etu/.bashrc

_baseName=tcp_syslog-ng.etu-5.log-hourly-CST-
_hdfs_path=.
_syslog_src=/home/jason ;cd $_syslog_src

nf=`ls |grep $_baseName | wc -l`

if [ $nf -gt 0 ]; then
   echo "foiund $nf syslog files ..."
   for i in `ls | grep $_baseName`
   do
     if [ -f $i.copied ]; then
        echo "syslog file $i not yet upload to HDFS"
     echo "create lock file for $i and start transferring to HDFS ..."
        hadoop fs -put $i $_hdfs_path
     echo $i >> $_syslog_src/upload.files
        echo "moving transferred file into archive"
        mv $i archive/
     gzip archive/$i
        echo "cleanup lock file"
        rm $i.copied
     else
        echo "syslog file $i not yet tranferred completed"
     fi
   done
else
   echo "cant find any syslog files"
fi
# archive/tcp_syslog-ng.etu-5.log-hourly-CST-2013052917 
