#!/bin/bash

_parse_lane () {

   ll=(`grep -n '<lane vsrdir' $1 | awk -F':' '{print $1}'`)
   local k=1
   local em=${#ll[@]}
   local max=${ll[-1]}
   local min=${ll[1]}
   for m in ${ll[@]}
   do
      if [ $max == 1 ]; then
         awk '{if(NR == '"$m"'){print $0}}' $1 | awk -F'"' '{printf "%s,%s,%s,%s",$2,$4,$6,$8}'
         grep '<cars carid' $1 | awk -F'"' '{printf ",%s,%s",$2,$4}'
      else
         if [ $k -eq $em ]; then
            awk '{if(NR == '"$m"'){print $0}}' $1 | awk -F'"' '{printf "%s,%s,%s,%s",$2,$4,$6,$8}'
            awk '{if(NR > '"$max"'){print $0}}' $1 | grep '<cars carid' | awk -F'"' '{printf ",%s,%s",$2,$4}'
         else
            ii=$m
            ee=${ll[$k]}
            awk '{if(NR == '"$m"'){print $0}}' $1 | awk -F'"' '{printf "%s,%s,%s,%s",$2,$4,$6,$8}'
            awk '{if(NR < '"$ee"' && NR > '"$ii"'){print $0}}' $1 | grep '<cars carid' | awk -F'"' '{printf ",%s,%s",$2,$4}'
         fi
      fi
      let k+=1
   done
   echo ""
  
}


nl=(`grep -n '<Info vdid=' $1 | awk -F':' '{print $1}'`)
tf=`mktemp /tmp/XXXXXX`
let j=1
el=${nl[1]}
for i in ${nl[@]}
do
   # <Info vdid="63000V03C0G0" status="0" datacollecttime="2013/04/01 00:00:00">
   if [ $j -gt ${#nl[@]} ]; then
      exit 0
   else
      awk '{if(NR == '"$i"'){print $0}}' $1 | awk -F'"' '{printf "%s,%s,%s",$2,$4,$6}'

      if [ $el -eq ${nl[-1]} ]; then
         awk '{if(NR > '"$el"'){print $0}}' $1 > $tf
      else
         il=$i
         el=${nl[$j]}
         awk '{if(NR < '"$el"' && NR > '"$il"'){print $0}}' $1 > $tf
      fi
      _parse_lane $tf
   fi
   let j+=1
done

rm -f $tf

# end
